### ISSUE TITLE
Success and fail icons not vertically centred

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#3857]
As part of the list actions, the success and fail icons are no longer vertically centred after an item has been uploaded/created/removed. Previously, their display was set to `inline-block` through CSS and they showed correctly. However, since the FontAwesome upgrade, jQuery is setting their display to `inline` when showing them, and this causes them to show too high.

Examples:

![screen shot 2014-08-26 at 16 39 43](https://cloud.githubusercontent.com/assets/109850/4047437/24351e04-2d3a-11e4-80e4-c584420c83da.png)

![screen shot 2014-08-26 at 16 41 48](https://cloud.githubusercontent.com/assets/109850/4047436/2433b7d0-2d3a-11e4-9ca2-50d9d98744f7.png)

**Comment by sathomas** [comment]
merge de-conflicted. to @nicolaasmatthijs
