### ISSUE TITLE
(A11y severity 1) Allow keyboard "escape" from collaborative documents

### ISSUE THREAD

**Issue by sathomas** [oaeproject/3akai-ux#3912]
Once a keyboard user enters the text entry frame and begins typing, the user then becomes trapped within the text field with no way to get out. Provide a method for users to leave the frame.

**Comment by JohnMcLear** [comment]
@sathomas are you still working on this?

**Comment by sathomas** [comment]
@JohnMcLear not in the very short term (next week or so), but possibly after that.

**Comment by JohnMcLear** [comment]
@sathomas okies I'm due to start working on this possibly this week so if you can free some time up over the next few days we can work together to get it done quickly?

**Comment by JohnMcLear** [comment]
Even just creating my a checklist of stuff to do would help, my notes are here: http://john.primarypad.com/ogf-24-03-15

**Comment by sathomas** [comment]
Closing this since the latest release of etherpad, combined with https://github.com/oaeproject/ep_oae/pull/13, addresses the issue
