### ISSUE TITLE
(A11y severity 4) Infinite scroll footer visibility

### ISSUE THREAD

**Issue by sathomas** [oaeproject/3akai-ux#3956]
Allow easier navigation to footer on infinite scroll pages.

It would be nice, though, if we could come up with a way to make the footer available on pages with infinite scrolling. Something like pinning it to the bottom of the window (`position: absolute; bottom: 0`) and then adding an opacity gradient to the bottom 50 pixels or so of content to make it clear that more content is available below the window. Kind of like what Amazon does with their "Read More".

**Comment by sallakarppinen** [comment]
Closing this as solving #3955 should be enough.
