### ISSUE TITLE
(Bug Bash) Android Issues

### ISSUE THREAD

**Issue by sathomas** [oaeproject/3akai-ux#3960]
Not sure how much (if any) we want to fix, but documented for posterity:

Android 4.1.1 on a [Huawei Prism II](http://consumer.huawei.com/us/mobile-phones/tech-specs/u8686-us.htm#anchor) smart phone.

**With the default web browser**

The `min-width: 400px` design doesn't fit on the screen

![unnamed-2](https://cloud.githubusercontent.com/assets/1731910/5457784/345af8f6-851b-11e4-8067-b0ed9f62eceb.png)

In additions, the `.woff` format icon font is not supported

![unnamed-1](https://cloud.githubusercontent.com/assets/1731910/5457788/408e24f4-851b-11e4-9aa2-23b9f428d3c5.png)

And the site is basically not navigable

![unnamed](https://cloud.githubusercontent.com/assets/1731910/5457798/5c054a64-851b-11e4-9822-73001afb6724.png)

**With Firefox 34.0**

The `min-width: 400px` design doesn't fit on the screen

![screenshot_2014-12-16-11-39-48](https://cloud.githubusercontent.com/assets/1731910/5457812/7157c9f0-851b-11e4-86e8-478b5a0b8a02.png)

However, all other functionality seems to work okay.

**With Chrome 39.0.2171.93**

Everything works as expected

![screenshot_2014-12-16-11-53-46](https://cloud.githubusercontent.com/assets/1731910/5457824/8aa408c4-851b-11e4-8a89-f2d17482eac0.png)

**Comment by nicolaasmatthijs** [comment]
Moving to the technical backlog as this won't be an immediate priority
