### ISSUE TITLE
URLs are wrapped in Markdown even within Markdown's own code blocks

### ISSUE THREAD

**Issue by designorant** [oaeproject/3akai-ux#3971]
*Please bear in mind this is likely a borderline case as I was trying to show how to point to particular comments in OAE**

I kind of understand why a plain text URL like this:
[https://tenancy.oaeproject.org/content/rr/7kNZsauE#1421426964990#1421427032981|](https://tenancy.oaeproject.org/content/rr/7kNZsauE#1421426964990#1421427032981|)
would get wrapped in Markdown automatically and show up like this:
[/content/rr/7kNZsauE#1421426964990#1421427032981|](https://tenancy.oaeproject.org/content/rr/7kNZsauE#1421426964990#1421427032981|)

However, this also happens if I put the URL in Markdown wrapped with back-tick quotes.

##### Code:
````
`https://tenancy.oaeproject.org/content/rr/7kNZsauE#1421426964990#1421427032981|`
````

##### Expectation:
`https://tenancy.oaeproject.org/content/rr/7kNZsauE#1421426964990#1421427032981|`

##### Result:
`[/content/rr/7kNZsauE#1421426964990#1421427032981|((/content/rr/7kNZsauE#1421426964990#1421427032981|)`
<br>
---
\*this is actually very handy although cumbersome as lazy loading gets in a way there

**Comment by nicolaasmatthijs** [comment]
Assigning to @stuart for fix. @stuartf: Didn't we recently put something in place to fix something like this?

**Comment by nicolaasmatthijs** [comment]
Actually, I misread that the first time around. This does indeed seem like a real edgecase, so I would only fix this if it is a very low-maintenance fix.

**Comment by stuartf** [comment]
This is actually a back end issue: https://github.com/oaeproject/Hilary/issues/1120
