### ISSUE TITLE
Permissions Bug

### ISSUE THREAD

**Issue by shwetaarora3** [oaeproject/3akai-ux#3974]
BUG
Category: Permissions/Roles
Summary: Manager Role entry for the resource instance, group which is visible in tenancy and open to join, does not get deleted.

Description:

Example 1
Test Data: Group which is visible to tenancy and "Anyone can join"
Join group
Go to "My Groups".
Select the checkbox next to that group and leave group.
You have successfully left the group and are not listed in its members.
But that group is still visible in "My groups" but you are not in the members list and you see the button which says "Join group"
Make an attempt to leave that group to which you have no access.
You get message:
The group could not be left.
Make sure at least one manager remains before leaving a group.

Example 2
Test data: Membership to a private group indirectly through a group which is visible to tenancy and which can be joined by anyone
Steps:
Parent group private - member is child group
Child group open to join - visible tenancy
Join child group - you see both parent and child group in "My Groups"
Leave child group: you see parent group in "My groups"
Make an attempt to leave parent group to which you have no access.
You get message:
The group could not be left.
Make sure at least one manager remains before leaving a group.

Conclusion:
1) When the person joins the group, the membership is added first, then the roles.
2) When the person is leaves the group, role entry is deleted first, then the GroupMembership.
3) This leaves behind a manager role entry for the resource instance, by virtue of direct association and indirect group inheritance, at the highest level.

**Comment by nicolaasmatthijs** [comment]
@shwetaarora3 : I've been able to confirm that the group is not correctly removed from the My Groups list. I'm going to move this ticket to our back-end bug tracker.

**Comment by nicolaasmatthijs** [comment]
Back-end ticket can be found at https://github.com/oaeproject/Hilary/issues/1128
