### ISSUE TITLE
Ensure that re-authenticating on mobile devices is not required

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#3981]
We have received a fair amount of feedback around the need to re-authenticate on mobile devices. Most people seem to expect that re-authentication on a mobile device should not be required. Therefore, we should be using cookies with a longer expiration (30 days to start off with?) on mobile devices.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment]
Addressed in https://github.com/oaeproject/Hilary/pull/1135
