### ISSUE TITLE
CreateLink: When editting the displayName, the text is cut off

### ISSUE THREAD

**Issue by simong** [oaeproject/3akai-ux#3982]
Pretty minor issue:

1. Click create new link
2. Fill in a link
3. Hit next
4. Focus on the displayName and fill in something else
5. The first character of your entered text is missing one or two pixels. It's pretty clear with an `O` or `T` character

![example](https://s3.amazonaws.com/f.cl.ly/items/0c0I2W273a1445042B32/Screen%20Shot%202015-03-10%20at%2015.03.29.png)

**Comment by mrvisser** [comment]
This is reproduceable on Chrome.

**Comment by mrvisser** [comment]
And Safari. One annoying thing is that it covers up the blinking cursor when you go to the start of the edit box, so you don't know if you're in a "typing mode" anymore.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Would you be able to have a look at this so we can include it in the upcoming release?

**Comment by mrvisser** [comment]
@nicolaasmatthijs ah, sure thing. I'll hop over to it.

**Comment by mrvisser** [comment]
Closing in favour of #3983
