### ISSUE TITLE
Follow up on #3983

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#3985]
The following regressions were found when testing the fixes for https://github.com/oaeproject/3akai-ux/pull/3983/files:

- On Chrome, the jeditable field jumps down by 1 pixel when switching to edit mode
- The edit version of the jeditable field doesn't stretch as far as the view mode

![screen shot 2015-03-11 at 22 02 01](https://cloud.githubusercontent.com/assets/109850/6612674/f46c5580-c83d-11e4-80d8-85cd46d61ce1.png)

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser

**Comment by simong** [comment]
FWIW, This happens in production as well and isn't necessarily a regression from #3983

**Comment by mrvisser** [comment]
Yea I found it happened on production as well which is why I didn't wrestle with it more to fix that one pixel on Chrome. I can keep looking at it but it's not going to be a case of just mingling a couple margins, I'll have to do some experimentation and hopefully something works.

**Comment by nicolaasmatthijs** [comment]
Yeah, both of these happen on production as well. @mrvisser : Do you know how difficult it would be to only fix `The edit version of the jeditable field doesn't stretch as far as the view mode` ?

**Comment by mrvisser** [comment]
@nicolaasmatthijs not at the moment, I'll look into it

**Comment by mrvisser** [comment]
Note that this will not be possible with IE9, but we can make the `h3` for the item name 100% on other browser without causing wrapping, then give the `input` for the editable field a width of `100%`. But we should only let the `h3` be full width when it is editable, or else the fly-overs look funny.

**Comment by mrvisser** [comment]
Closing in favour of #3988
