### ISSUE TITLE
URGENT Group Home Page Blank

### ISSUE THREAD

**Issue by JoshBaron** [oaeproject/3akai-ux#3989]
I've just been alerted to an issue with OAE group ins our main Marist OAE instance.  I've been able to replicate in on my computer (Windows 8.1 FireFox 36.0.1) but have not researched beyond this....

When you go to a Group site you get the outside frame of the page but not the activity feed or navigation.  A good example is: https://marist.oaeproject.org/group/marist/lyJ02SmQp

In addition to normal concerns over such things, we are using OAE for collaboration associated with the LAK conference and folks have critical documents in Groups that we cannot access.  Thus, there is significant concern here at the moment.

Josh

**Comment by nicolaasmatthijs** [comment]
This appears to be a back-end bug. I'll close this ticket to allow us to track work in https://github.com/oaeproject/Hilary/issues/1141
