### ISSUE TITLE
Visual regression in email notifications

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#3990]
![screen shot 2015-03-13 at 08 04 38](https://cloud.githubusercontent.com/assets/109850/6640909/a6467708-c957-11e4-9878-7a613ff9d2ff.png)

As you can see, the title of the activity is too close to the profile picture. In the comment, you can also see that the text flows underneath the profile picture.

The padding inside of the tile itself seems to be messed up as well.

The text size also seems to have increased, but maybe we can leave that as is.

**Comment by nicolaasmatthijs** [comment]
FWIW, I think this may be a regression caused by one of the a11y fixes

**Comment by mrvisser** [comment]
@nicolaasmatthijs would you be able to forward me this email?

**Comment by nicolaasmatthijs** [comment]
I've received feedback about another visual regression, even after we rolled back to the previous version of juice. The tile for an item looks off. There is too much line spacing with the title, ideally it wouldn't stretch to 3 lines and the visibility icon is too small and should now be positioned next to the type per the main UI.

![img_0343](https://cloud.githubusercontent.com/assets/109850/6721903/aa8e8a62-cd8f-11e4-90ed-dc27f141e827.PNG)

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Is any additional work required here?

**Comment by mrvisser** [comment]
@nicolaasmatthijs any required work would be to get juice up to the latest version again.

**Comment by nicolaasmatthijs** [comment]
Closing in favor of #4007
