### ISSUE TITLE
Provide translations for custom Etherpad functionality

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#3991]
Currently, we hardcode `Toggle Authorship Colors`, `Download` and the `Style` dropdown to English strings. We should make these internationalised.

**Comment by nicolaasmatthijs** [comment]
@simong @mrvisser Any idea on what the best approach would be here? Preferably, we would be able to use translations from our Crowdin account.

**Comment by simong** [comment]
We could spend a bit of time on localizing `ep_oae` (see http://etherpad.org/doc/v1.3.0/#index_localizing_plugins for more info). Maybe `ep_oae` keys could be prefixed with `ep_oae_` and we could write a little script to sync it up with crowdin?

**Comment by nicolaasmatthijs** [comment]
Assigning to @stuartf

**Comment by nicolaasmatthijs** [comment]
Assigning to @Coenego for fix. @simong : Can you provide a bit of guidance on the development approach to take here.

**Comment by nicolaasmatthijs** [comment]
Apparently @stuartf started work on this yesterday and has been making some good progress. Therefore, assigning this back to @stuartf .

**Comment by stuartf** [comment]
https://github.com/oaeproject/ep_oae/pull/12

**Comment by nicolaasmatthijs** [comment]
Closing this in favour of oaeproject/ep_oae#12
