### ISSUE TITLE
A link without a protocol can't be openened on the profile page

### ISSUE THREAD

**Issue by simong** [oaeproject/3akai-ux#3993]
I can't recall how I did this, but I created a link without a protocol (e.g., `www.google.com` rather than `http://www.google.com`) when I try to click the `Open link` button, the link is appended to the current page (so it becomes `https://oae.gatech.edu/content/gatech/7kCu65zK/www.google.com`).

See https://oae.gatech.edu/content/gatech/7kCu65zK for an example.

**Comment by nicolaasmatthijs** [comment]
@simong How did you create this link? The createlink widget should be prepending `http://` to all links that don't have a protocol set.

**Comment by simong** [comment]
![Magic!](https://brentwoodtwinningmontbazon.files.wordpress.com/2012/03/magic0021.gif)

Seriously though, I just remembered: I was demonstrating the Swagger Docs to David. As we have an API, we probably shouldn't rely on the `createlink` widget always prepending `http://`.

**Comment by nicolaasmatthijs** [comment]
We should probably just prepend the protocol upon link creation. I'll create a Hilary ticket for this.
