### ISSUE TITLE
Over-aggressive markup of numbered lists in comments

### ISSUE THREAD

**Issue by WilliamCB** [oaeproject/3akai-ux#3995]
Numbering of lists specified by the user is often overridden by the markup logic, changing the numbering. Cases where this happens:
- non-natural ordering, eg a list with numbering 1. 2, 4 and 7. In this case the numbers 4 and 7 will be changed to 3 and 4
- multi-paragraph list items, where item 1 in the list has four paragraphs for example. In this case the next number in the list will be changed from 2 to 1.

**Comment by simong** [comment]
> non-natural ordering, eg a list with numbering 1. 2, 4 and 7. In this case the numbers 4 and 7 will be changed to 3 and 4

We're using a plugin that [uses markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists) to generate the formatting. Unfortunately this is the way markdown works. Markdown will generate the list numbers for an ordered list.

That said, to me this suggests that numbers might not have the correct semantical meaning and it might be better to use asterisks or dashes for listing things out?

> multi-paragraph list items, where item 1 in the list has four paragraphs for example. In this case the next number in the list will be changed from 2 to 1.

This might be a to advanced feature of markdown, but we do support combining lists with paragraphs. The paragraphs have to be indented with spaces however (at least one space). For example,

```
1. This

   is my indented

   first item
2. Second item
3. Third
    
   item
```

should generate:

1. This

   is my indented

   first item
2. Second item
3. Third
    
   item

**Comment by mrvisser** [comment]
I might just add, you can tell Markdown's list processing to go away by "escaping" the `.` that follows the number (http://stationinthemetro.com/wp-content/uploads/2013/04/Markdown_Cheat_Sheet_v1-1.pdf):

### Regular numbered list item processing:

Code:

```
1. This is a list
1. that uses mark-down auto-numbering
1. thanks Markdown!
```

Result:

1. This is a list
1. that uses mark-down auto-numbering
1. the horror!

### Escaped numbered list item processing:

Code: 
```
1\. This is a list
1\. that escapes mark-down auto-numbering
1\. thanks Markdown!
```

Result: 

1\. This is a list
1\. that escapes mark-down auto-numbering
1\. thanks Markdown!

**Comment by WilliamCB** [comment]
Well, I can see the software is performing as it is designed to. But, as a user, my point of view is that anything that actually changes the content and meaning of what I wrote is a bug. 

I would add that we can't expect users to understand that there is a markdown syntax at work, let alone what it is. It's nice to have additional features for experts, but in my view for most users it just has to work. In general, the OAE is very good at this and I see this as an exception.

**Comment by nicolaasmatthijs** [comment]
I agree with @WilliamCB that even though this is in line with the Markdown spec, this doesn't necessarily mean that it's expected behaviour. Users should not have to be aware of Markdown to be able to use OAE commenting effectively.

I've just tried the various configuration options for the plugin we're using, and none of them seem to affect the list ordering problem. I'm not entirely sure what the right next step is here. We could accept this bug in the light of the additional features and maintainability that Markdown gives us. Or we could remove the Markdown parser and implement the features that we like ourselves, adding a maintenance cost.

**Comment by WilliamCB** [comment]
Can we not improve the parser itself?

**Comment by nicolaasmatthijs** [comment]
@stuartf : How difficult would it be to add a configuration option for ordered lists to the plugin and contribute it back?

**Comment by WilliamCB** [comment]
A sort of work around on this might be to give users the option to prevent markdown being applied.

**Comment by nicolaasmatthijs** [comment]
The escaping method using `\` is already in place to address it, but that again requires users to be somewhat aware of the Markdown parser

**Comment by WilliamCB** [comment]
Sorry, I wasn't clear. I was thinking of a button on the Comments panel that when clicked prevents markdown being applied to the entire comment.

**Comment by nicolaasmatthijs** [comment]
Whilst I understand that such a button could be helpful for power users like yourself, it would still be exposing a level of technical detail that users should not have to be aware of and could become confused by.

**Comment by stuartf** [comment]
The markdown processor we use is https://github.com/chjj/marked and I think this would be a pretty big patch as currently it tokenizes the list making note of if it's ordered or not, and discards the bullets (which are the numbers in the case of an ordered list), then for ordered lists it renders them in html using `ol` and `li` tags.

**Comment by SamPeck** [comment]
I'm not sure we should be trying to solve the problem of how to extend the
discussion and commentary capability in the OAE from the position of a
quick and simple plug in, added to what is still essentially a foundational
feature like comments.

On Tuesday, March 24, 2015, D. Stuart Freeman <notifications@github.com>
wrote:

> The markdown processor we use is https://github.com/chjj/marked and I
> think this would be a pretty big patch as currently it tokenizes the list
> making note of if it's ordered or not, and discards the bullets (which are
> the numbers in the case of an ordered list), then for ordered lists it
> renders them in html using ol and li tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oaeproject/3akai-ux/issues/3995#issuecomment-85607812>
> .
>


-- 

Sam Peck
User Experience Consultant

HMS President (1918)
London EC4Y 0HJ
Victoria Embankment

Web  sampeckconsulting.com <http://www.sampeckconsulting.com/>
Twitter  5amPeck <http://www.twitter.com/@5ampeck>
Email sam@sampeckconsulting.com

**Comment by nicolaasmatthijs** [comment]
@SamPeck : I'm not sure I fully understand what you mean. We already have a markdown plugin to provide some basic formatting like adding bullet points for lists, etc. but it's sometimes a bit too aggressive in its parsing. Are you suggesting that we don't need something like this at all or that there are bigger priorities around commenting than fixing this particular bug?

**Comment by SamPeck** [comment]
@nicolaasmatthijs The latter, I believe we are trying to fix something that might be better solved amongst a wider benefit or more holistic effort.

**Comment by SamPeck** [comment]
@nicolaasmatthijs Basically not sure it's a bug, but a "bugbear".

**Comment by WilliamCB** [comment]
I suspect @SamPeck is right when he says, "I believe we are trying to fix something that might be better solved amongst a wider benefit or more holistic effort"

**Comment by nicolaasmatthijs** [comment]
Fair enough. I'm going to close this ticket in favor of a more holistic design effort around commenting.
