### ISSUE TITLE
Search fails with 3-letter strings

### ISSUE THREAD

**Issue by WilliamCB** [oaeproject/3akai-ux#4004]
I have many documents with the acronym AfE in them. Searching for these documents with the string "AfE" does not produce the documents in the list. However, searching for the full "Awareness for Everyone" string returns all the documents at the top of the list.

I have previously noticed this issue with "csv".

**Comment by nicolaasmatthijs** [comment]
Added this to a more general search improvements ticket at https://github.com/oaeproject/Hilary/issues/1162
