### ISSUE TITLE
Allow group profile to be seen by non-members for private joinable groups

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/3akai-ux#4009]
They should also be able to see the featured members feed in the profile. Generally we don't reveal members, however if a user can simply join the group, there is no privacy being protected by restricting it.

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Is it possible to see the activity feed before joining as well?

**Comment by mrvisser** [comment]
Depends if we have `#loggedin` / `#public` feeds for groups.

**Comment by nicolaasmatthijs** [comment]
Incorporating into the design backlog
