### ISSUE TITLE
encodeForHTMLAttribute seems to mis-encode backslash

### ISSUE THREAD

**Issue by simong** [oaeproject/3akai-ux#4010]
Steps to reproduce:

1. Create a link
2. Go to the link profile
3. Go to the "edit details" page
4. Change the displayName to `foo\test`
5. Click the save button so the edit details modal closes
6. Click the edit details button again
7. The displayName input field will now contain `foo�`

The result looks like: ![](https://cldup.com/LCgyy-yt3V-3000x3000.png)

This is particularly obvious when checking the email domain regexes (regardless of their use)

**Comment by nicolaasmatthijs** [comment]
Assigning to @stuartf for fix

**Comment by stuartf** [comment]
This isn't happening on my checkouts of master

**Comment by nicolaasmatthijs** [comment]
@simong : Can you provide some additional instructions here?

**Comment by simong** [comment]
So far I've been able to reproduce this on QA0 on:

Mac OS X 10.10.1:
 - Chrome 42.0.2311.90
 - Safari Version 8.0.2 (10600.2.5)
 - Firefox 37.0.2

Windows 8:
 - Internet Explorer 10
 - Firefox latest

**Comment by simong** [comment]
I just noticed that the instructions might not be entirely clear. I've updated them to:

1. Create a link
2. Go to the link profile
3. Go to the "edit details" page
4. Change the displayName to `foo\test`
5. Click the save button so the edit details modal closes
6. Click the edit details button again
7. The displayName input field will now contain `foo�`

**Comment by simong** [comment]
Back to @stuartf

**Comment by stuartf** [comment]
Ah, I was just making the displayname `foo\` which works as expected, so it appears to be an issue with `\` followed by a character.

**Comment by stuartf** [comment]
This is an upstream issue: https://github.com/chrisisbeef/jquery-encoder/issues/5

**Comment by nicolaasmatthijs** [comment]
@stuartf : Is there an easy fix that we can contribute back upstream? If not, we should probably close this ticket in favour of the upstream one, which I'm now watching
@simong : Is this a big issue for the email domain regexes?

**Comment by simong** [comment]
Not really as they will probably be refactored into something else

**Comment by nicolaasmatthijs** [comment]
In that case, closing this ticket in favour of upstream issue
