### ISSUE TITLE
(A11y) Color picker in admin skinning page not keyboard accessible

### ISSUE THREAD

**Issue by sathomas** [oaeproject/3akai-ux#4030]
We may not want to address this at this time, but as a note, the color picker that's used throughout the admin skinning interface is not keyboard accessible at all.

**Comment by nicolaasmatthijs** [comment]
As this is an admin-only feature, moving this to the technical backlog.

@sathomas : In the meantime, would you be able to create a ticket for this in the colorpicker repo?

**Comment by sathomas** [comment]
Already exists. https://github.com/bgrins/spectrum/issues/295
