### ISSUE TITLE
Error when starting Hilary cause by too many bundles

### ISSUE THREAD

**Issue by Coenego** [oaeproject/3akai-ux#4039]
When spinning up Hilary (on OSX), a list of errors are shown saying that the bundle files can't be opened; 

```
Error: EMFILE, open '/Users/md623/projects/apereo/oae/3akai-ux/node_modules/oae-core/uploadnewversion/bundles/zh_CN.properties'
--
path: /node_modules/oae-core/uploadnewversion/bundles/zh_CN.properties
```

Currently fixed it locally by changing the number of maximum allowed open files (`ulimit -n` from 256 to >1000)

**Comment by sathomas** [comment]
Interesting. I don't see the problem on 10.10.4 running current Hilary master.

```
bash-3.2$ ulimit -n
256
bash-3.2$
```

**Comment by simong** [comment]
Although there are over 700 .properties files, this is more of a Hilary issue. Hilary should probably not try to open 700 files in one go.

@sathomas: I occasionally ran into this issue and had to bump my ulimit settings to 1000+ as well. I suppose it depends on how fast node can process (and close) the open files?

**Comment by nicolaasmatthijs** [comment]
Created Hilary ticket at https://github.com/oaeproject/Hilary/issues/1220

**Comment by davidoae** [comment]
Could they be combined into 1 file, or a small number?
