### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by sathomas** [oaeproject/3akai-ux#4041]
Might be related to https://github.com/oaeproject/Hilary/issues/1222

Immediately after logging into the guest tenancy, I went back to the original tenancy. The notifications icon had a badge of 2, but clicking on it just shows an empty container. Errors in the console:

```
[Error] Failed to load resource: the server responded with a status of 418 (Bad Request) (markRead, line 0)
[Error] An error has occured while retrieving the list of results
	error (oae.core.7b0b5116.js, line 1)
	f (require-jquery.3f5c3fe4.js, line 1)
	fireWith (require-jquery.3f5c3fe4.js, line 1)
	S (require-jquery.3f5c3fe4.js, line 1)
	(anonymous function) (require-jquery.3f5c3fe4.js, line 1)
```

**Comment by mrvisser** [comment]
Filed at the mentioned issue
