### ISSUE TITLE
(InvitingGuests) - Activity feedback

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4042]
- 'Has invited you to share ...' sounds a bit strange to me. I've been invited to the content item, but I haven't been invited to share it.
- "Nicolaas Matthijs has accepted an invitation to add the file "i hate everything.gif" to their library" is currently showing the picture of the user that invited you. However, per the regular activity feed, this should show the content item preview.
- We should have a "You" version of invitation accept activities that is used when you are the actor in the activity (i.e. `You have accepted Branden Visser's invitation to the group Wiggle`). In the main activity feed, we have "You" version as well.

**Comment by mrvisser** [comment]
> 'Has invited you to share ...' sounds a bit strange to me. I've been invited to the content item, but I haven't been invited to share it.

I thought it was strange too, but interpreted it as the user who invited them, was inviting them in order to share with them.

What would you recommend?

**Comment by mrvisser** [comment]
> We should have a "You" version of invitation accept activities that is used when you are the actor in the activity (i.e. You have accepted Branden Visser's invitation to the group Wiggle). In the main activity feed, we have "You" version as well.

I'll do this for both actor and object. So we would have both:

`You have accepted Branden Visser's invitation to the group Wiggle`; and
`Nicolaas Matthijs has accepted your invitation to the group Wiggle`

**Comment by nicolaasmatthijs** [comment]
+1

**Comment by mrvisser** [comment]
Fixed in 83227d2..b2e1f3c
