### ISSUE TITLE
(InvitingGuests) - Invalid error message

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4043]
<img width="509" alt="screen shot 2015-08-04 at 08 14 54" src="https://cloud.githubusercontent.com/assets/109850/9065521/c38a60d6-3a86-11e5-82c6-84537258ea17.png">

**Comment by mrvisser** [comment]
Fixed in https://github.com/oaeproject/3akai-ux/commit/83227d20792887ab16e99241a182edba233aabc4
