### ISSUE TITLE
(InvitingGuests) - Members list is empty after adding group member

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4045]
I created a new group and added an existing user using their email address. After saving, the member list was empty. Refreshing the page solved the problem.

**Comment by mrvisser** [comment]
@nicolaasmatthijs was this while the server was having issues?

**Comment by nicolaasmatthijs** [comment]
@mrvisser : This happened after the server issues. FWIW, I was using Safari.

**Comment by mrvisser** [comment]
This is not reproduceable when the server is stable
