### ISSUE TITLE
Mistake in the error notification of "Create Tenant"

### ISSUE THREAD

**Issue by D7Torres** [oaeproject/3akai-ux#4052]
When an alias already in use or a host already in use are used in the creation of a tenant, the corresponding endpoint returns the correct error. However, the notification is not showed in the UI because `jqXHR` is not defined in that context.

In `3akai-ux/node_modules/oae-admin/tenants/js/tenants.js` line: 249

change

`jqXHR.responseText`
to

`err.msg,`

**Comment by mrvisser** [comment]
Thanks for the report @D7Torres , I actually caught this bug earlier and have a fix lined up in another feature branch that is in PR: https://github.com/oaeproject/3akai-ux/pull/4051/files#diff-e8b18eaf86d7efa64fd0666f02e0dcebL249
