### ISSUE TITLE
Spacing problem in etherpad after copying from MS-Word

### ISSUE THREAD

**Issue by Parasuram15** [oaeproject/3akai-ux#4056]
Hi there,

When we create a new document in OAE (link: https://marist.oaeproject.org ) by copying the content from a Word document, we see random deleted spaces between words.  See attached snapshots.

In addition, the visual clue for random deleted spaces can be seen in 'can manage' or 'can edit'  mode under the 'manage access' option, which doesn't appear in 'can view' option. But, the issue remains the same.

Screenshot for 'can manage' or  'can edit' mode:
![canmanage](https://cloud.githubusercontent.com/assets/14299999/9888554/b81f244e-5bc3-11e5-806c-6cc882b78961.PNG)

Screenshot for 'can view' mode:
![capture1](https://cloud.githubusercontent.com/assets/14299999/9888635/323c01a2-5bc4-11e5-9789-57200d808977.PNG)

**Comment by RoliShrivastava** [comment]
Hello,
In addition to the above issue, we are facing another issue.
Issue: When we save the document as a file (Document -> Print -> Save As -> Name.PDF), few special characters are getting embedded  and replacing the punctuation symbols in the document saved.
Please refer the attached image file.

![capture](https://cloud.githubusercontent.com/assets/14316465/9911049/35c4291c-5c6e-11e5-9883-d47c6eb7dad9.PNG)

**Comment by nicolaasmatthijs** [comment]
@Parasuram15 : Would you be able to paste the content of the Word document in the stand-alone Etherpad demo at https://beta.etherpad.org. Are you seeing the same behaviour there too?

**Comment by Parasuram15** [comment]
@nicolaasmatthijs :

As directed, we have tested the same scenario on Etherpad and we can still find the random deleted spaces in between.

Please find the attached tested document. 

In the attached snapshot, the text highlighted in 'blue color' is copied from 'Notepad' and the text highlighted in 'red color' represents the copied text from ' Ms Word'. 

Found: We can see this behavior specifically when we copy the text from Ms Word.

@RoliShrivastava :+1: 

![etherpad](https://cloud.githubusercontent.com/assets/14299999/9994825/1489d75a-604d-11e5-82fa-076d4de7f592.PNG)

**Comment by nicolaasmatthijs** [comment]
@Parasuram15 : As you are able to reproduce the same problem on the out-of-the-box Etherpad installation, it looks like you've uncovered a more general Etherpad bug. Therefore, would you be able to create this ticket in the Etherpad repository (https://github.com/ether/etherpad-lite/issues) and attach the Word file to that ticket?
