### ISSUE TITLE
Problem with timeago in French

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4067]
![1443017388](https://cloud.githubusercontent.com/assets/109850/10047326/7d3bb78e-61c2-11e5-9a62-ed97dbf4582b.png)

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by dooremont** [comment]
thanks

**Comment by mrvisser** [comment]
This was probably seen as a result of a trailing space being removed after `\`. A crowdin sync appears to have added it back in, so this is no longer reproducable.
