### ISSUE TITLE
Push notifications not aggregating as expected

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4069]
There appears to be a problem with the client side aggregation of push notifications in the activity feed. As I was looking at the activity feed, someone was uploading content items into a folder. This resulted in a separate activity for each content item, rather than performing the client side aggregation we expect.

<img width="1414" alt="screen shot 2015-09-23 at 08 42 38" src="https://cloud.githubusercontent.com/assets/109850/10050341/ac0b7e74-61d0-11e5-9801-c3156307cf75.png">

Once the page is refreshed, things are properly aggregated.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment]
@nicolaasmatthijs it is expected that they would appear separately outside of a hard-coded delay. Can you confirm that it is still not aggregating within the confines of the delay?

**Comment by nicolaasmatthijs** [comment]
They appeared to be coming in with less than a second between them, but maybe it was just over a second. If it is just a timeout issue, maybe it's worth considering bumping the timeout to a few seconds?

**Comment by mrvisser** [comment]
It depends on how long of a delay you think is acceptable for push notifications. The user won't see any new activity -- including their own actions -- for that duration of time.

**Comment by nicolaasmatthijs** [comment]
Ah, right. It includes their own actions. Lets keep it as is then.

Were you able to confirm that the aggregation is working when new content items come in with < 1 second of interval?

**Comment by mrvisser** [comment]
Yes that seems to be working fine. I'll close this until a more deterministic case pops up that shows it not working.
