### ISSUE TITLE
Icon display in etherpad for authorship and download unclear/changed

### ISSUE THREAD

**Issue by corrinicoletti** [oaeproject/3akai-ux#4082]
When using the etherpad today in production, we noticed the icons are not displaying correctly.

[oaeicons](https://cloud.githubusercontent.com/assets/15199786/10584283/515defa4-765f-11e5-8a06-526fa0d878d2.PNG)

**Comment by simong** [comment]
Thank you for spotting this @corrinicoletti, we'll be rolling out a fix for this shortly.

**Comment by nicolaasmatthijs** [comment]
@simong : Can this ticket be resolved?

**Comment by simong** [comment]
Sure, with the caveat that the fix is in ep_oae master but hasn't been rolled out to production just yet.

**Comment by mrvisser** [comment]
I think we should keep this open until it's fixed in production.

**Comment by nicolaasmatthijs** [comment]
A fix for this has been deployed to production
