### ISSUE TITLE
Tenant links are no longer replaced in comments

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4086]
Tenant links are no longer recognized in comments and replaced by a relative version.

<img width="1576" alt="screen shot 2015-11-09 at 22 12 59" src="https://cloud.githubusercontent.com/assets/109850/11055757/103d407a-872f-11e5-84e8-a60cacb0d021.png">

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment]
Believe it or not, this only happens if the tenant host contains the letter `s` or `n` in it.... our tests cover link replacing with `cambridge.oae.com`

:(

**Comment by mrvisser** [comment]
PR is submit here: https://github.com/oaeproject/Hilary/pull/1258

**Comment by nicolaasmatthijs** [comment]
Closing in favour of oaeproject/Hilary#1258
