### ISSUE TITLE
Admin UI drop down lists empty

### ISSUE THREAD

**Issue by davidoae** [oaeproject/3akai-ux#4088]
When using the admin UI, attempting to change a 'block' type the control is a drop down list, however that list has no options to select.
The only error I had in the console log was related to favicon.
I'm using;
Chromium	45.0.2454.101 (Developer Build) Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)

It worked fine with Firefox.

**Comment by sallakarppinen** [comment]
I cannot reproduce this locally on either Chrome or Chromium, @davidoae, so it could have been related to a particular build (I'm on Chromium 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)). Are you still experiencing the problem?

**Comment by nicolaasmatthijs** [comment]
Going to resolve this as "Cannot reproduce". @davidoae : Please re-open this ticket with additional information if you can reproduce this.
