### ISSUE TITLE
Hidden "Sign in with ..." button visible 

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4092]
The hidden "Sign in with ..." button that's used to automatically redirect a user to SSO when hitting an access denied page is visible in the page. This button should be hidden.

<img width="1720" alt="screen shot 2016-01-11 at 22 08 25" src="https://cloud.githubusercontent.com/assets/109850/12256146/02e9e772-b8b0-11e5-8dee-624910d44bea.png">

**Comment by mrvisser** [comment]
Assigned to @sallakarppinen

**Comment by sallakarppinen** [comment]
Interestingly this only seems to happen on tenants with *.oaeproject.org urls, not *.unity.ac ones.

**Comment by nicolaasmatthijs** [comment]
When an institution only has a single (external) authentication method, hitting `Sign in` should automatically bring you to that external authentication method's sign in page. If an institution has more than 1 authentication method, the sign in modal will be invoked to allow the user to pick which authentication method to use. As \*Research has both Google and local enabled, they get the modal. As Marist only has CAS enabled, they are sent to the CAS login page straight away.

The code that adds this "hidden" button to help with the redirect can be found in `oae.api.authentication.js` (`externalLogin`).

**Comment by sallakarppinen** [comment]
In that case, the extra button only appears for tenancies with a single authentication method, which makes sense. Also, the redirect (or modal) is happening as soon as I hit the 401 page, without clicking on 'Sign in'... Is this intentional or should the redirect/modal only be triggered on button press?

**Comment by nicolaasmatthijs** [comment]
@sallakarppinen : Yes, when you follow a link to something you don't have access to and you're not signed in yet, we will automatically redirect you to the login page.

**Comment by nicolaasmatthijs** [comment]
Closing this in favour of https://github.com/oaeproject/3akai-ux/pull/4101.

@sallakarppinen : Would you be able to use https://github.com/defunkt/hub to attach pull requests to existing issue? I think I recall that being deprecated, but it's okay to use it until a different method is in place.

**Comment by sallakarppinen** [comment]
As mentioned in #4101 description, I tried to do that and for some reason it created a separate pull request instead of linking it as expected. Possibly something to do with permissions, as I can't assign issues either.
