### ISSUE TITLE
Google Sign In button is temporarily visible

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/3akai-ux#4107]
Google Sign In button is temporarily visible when signing into a tenant with Google Authentication

<img width="1792" alt="screen shot 2016-06-02 at 08 34 52" src="https://cloud.githubusercontent.com/assets/109850/15751338/9eb170c2-289e-11e6-99be-91beaf33056b.png">

**Comment by nicolaasmatthijs** [comment]
Assigning to @sallakarppinen for fix

**Comment by sallakarppinen** [comment]
I can't reproduce this locally - any more info on how to reproduce?

**Comment by nicolaasmatthijs** [comment]
I noticed this during the bugbash on the Cambridge tenant, which had Google Authentication with a Google Apps domain configured. When I clicked Sign In, I could briefly see the `Sign in with Google` button appear at the bottom.

**Comment by sallakarppinen** [comment]
I have not been able to reproduce this locally or on RR Unity account (which has Google authentication) with either Chrome or Firefox. Which browser was used during bugbash? Is it happening on live deployment with the Cambridge tenant? (I don't have credentials so can't test it myself.)

**Comment by nicolaasmatthijs** [comment]
@sallakarppinen : I'm also no longer able to reproduce this. Closing this ticket.
