### ISSUE TITLE
Back button on 404/401 pages doesn't work on links from Etherpad

### ISSUE THREAD

**Issue by sallakarppinen** [oaeproject/3akai-ux#4142]
Links from Etherpad open in a new tab, so if an Etherpad link is broken the back button on the page doesn't work and the browser back button takes the user to the Etherpad doc itself, not to OAE. Solutions include: disabling the back button or making it close the tab when there's no history (?) and making sure the referrer is the page itself, not the doc.

**Comment by brecke** [comment]
> Solutions include: disabling the back button or making it close the tab when there's no history (?)

I don't think that's a good idea.

> and making sure the referrer is the page itself, not the doc.

☝️
