### ISSUE TITLE
Update Grunt & related

### ISSUE THREAD

**Issue by sallakarppinen** [oaeproject/3akai-ux#4173]
We should look into updating our Grunt version and it's dependencies. As part of this task we should also move to a optimisation library that understands ES6 instead of using require.js, and look into how we can make sure the automated tests are run for the UI.

Important resources for this task:

- https://engineering.wingify.com/posts/migrating-towards-yarn-webpack/

**Comment by brecke** [comment]
ES6 is now supported, except for file hashing which is disabled (for now)
